[package]
name = "securecart-api"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5.3"
axum = { version = "0.8.1", features = ["json"] }
jwt = "0.16.0"
regex = "1.11.1"
sea-orm = { version = "1.1.4", features = ["sqlx-postgres", "runtime-tokio-rustls"] }
serde = "1.0.217"
tokio = { version = "1.43.0", features = ["tracing", "rt-multi-thread"] } 
