[package]
name = "securecart-api"
version = "0.1.0"
edition = "2021"
description = "The API for the SecureCart ecommerce platform (my CCSE coursework)"
license = "MIT"
repository = "https://github.com/j-0-3/SecureCart"
readme = "../../README.md"
keywords = ["securecart"]
categories = ["web-programming"]

[dependencies]
argon2 = "0.5.3"
axum = { version = "0.8.1", features = ["json"] }
chrono = { version = "0.4.39", features = ["serde"] }
jwt = "0.16.0"
regex = "1.11.1"
serde = "1.0.217"
sqlx = { version = "0.8.3", features = ["chrono", "postgres", "runtime-tokio", "time"] }
time = { version = "0.3.37", features = ["macros"] }
tokio = { version = "1.43.0", features = ["tracing", "rt-multi-thread"] } 
