allowed-duplicate-crates = [
    # For targets I don't care about
    "windows-targets",
    "windows_aarch64_gnullvm",
    "windows_aarch64_msvc",
    "windows_i686_gnu",
    "windows_i686_msvc",
    "windows_x86_64_gnu",
    "windows_x86_64_gnullvm",
    "windows_x86_64_msvc",
    "windows-sys",
    "wasi",
    # Because aHash is using an outdated version (secure but annoying)
    "getrandom"
]
