services:
  db:
    build: backend/db
    secrets:
      - db_password

  redis:
    image: redis:latest

  api:
    build: 
      context: backend/api
      args:
        - DB_USERNAME=securecart
        - DB_DATABASE=securecart
        - DB_HOST=db
        - REDIS_HOST=redis
    secrets:
      - db_password
    profiles:
      - run
    ports:
      - 8080:8080

  dev:
    build: 
      context: dev
      args:
        - DB_HOST=db
        - DB_USERNAME=securecart
        - DB_PASSWORD=${DEV_DB_PASSWORD}
        - DB_DATABASE=securecart
        - REDIS_HOST=redis
    profiles:
      - dev
    volumes:
      - .:/root/app
    hostname: securecart-dev

  pgadmin:
    image: dpage/pgadmin4
    ports: 
      - 8000:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@securecart.com
      - PGADMIN_DEFAULT_PASSWORD=${DEV_DB_PASSWORD}
    profiles:
      - dev

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - 5540:5540
    profiles:
      - dev

  pgweb:
    image: sosedoff/pgweb
    ports:
      - 8081:8081
    profiles:
      - dev
    environment:
      - PGWEB_AUTH_USER=securecart
      - PGWEB_AUTH_PASS=${DEV_DB_PASSWORD}
      - PGWEB_DATABASE_URL=postgres://securecart:${DEV_DB_PASSWORD}@db/securecart?sslmode=disable


secrets:
  db_password:
    environment: DB_PASSWORD
