# Development service configuration. All configuration and secret values are hardcoded. Insecure, never expose publically.
services:
  db:
    build: backend/db
    environment:
      - POSTGRES_USER=securecart
      - POSTGRES_PASSWORD=securecart
      - POSTGRES_DB=securecart
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "securecart", "-d", "securecart"]
      interval: 30s
      start_interval: 5s
      start_period: 30s
      retries: 5

  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      retries: 5
      start_interval: 5s
      start_period: 30s

  api:
    build: 
      context: backend/api
    environment:
      - DB_USERNAME=securecart
      - DB_DATABASE=securecart
      - DB_HOST=db
      - REDIS_HOST=redis
      - DB_PASSWORD=securecart
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "/bin/healthcheck.sh"]
      interval: 30s
      retries: 5
      start_interval: 5s
      start_period: 30s
    develop:
      watch:
        - action: rebuild
          path: backend/api/src

  frontend:
    build: frontend
    healthcheck:
      test: ["CMD", "/bin/healthcheck.sh"]
      interval: 30s
      retries: 5
      start_interval: 5s
      start_period: 30s
    develop:
      watch:
        - action: sync
          path: frontend/src
          target: /usr/share/nginx/html/

  nginx:
    build: nginx
    ports:
      - 8443:8443
    healthcheck:
      test: ["CMD", "/bin/healthcheck.sh"]
      interval: 30s
      retries: 5
      start_interval: 5s
      start_period: 30s
    depends_on:
      frontend:
        condition: service_healthy
      api:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: nginx/nginx.conf
          target: /etc/nginx/nginx.conf
