//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "category")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::category_membership::Entity")]
    CategoryMembership,
}

impl Related<super::category_membership::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CategoryMembership.def()
    }
}

impl Related<super::product::Entity> for Entity {
    fn to() -> RelationDef {
        super::category_membership::Relation::Product.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::category_membership::Relation::Category.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
