//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "order_item")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub order_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub product_id: i64,
    pub count: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::apporder::Entity",
        from = "Column::OrderId",
        to = "super::apporder::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Apporder,
    #[sea_orm(
        belongs_to = "super::product::Entity",
        from = "Column::ProductId",
        to = "super::product::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Product,
}

impl Related<super::apporder::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Apporder.def()
    }
}

impl Related<super::product::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Product.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
