//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "password")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: i64,
    #[sea_orm(column_type = "Text")]
    pub password: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::appuser::Entity",
        from = "Column::UserId",
        to = "super::appuser::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Appuser,
}

impl Related<super::appuser::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Appuser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
