name: ci

on:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  cargo:
    defaults:
      run:
        working-directory: ./backend/api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: clippy
        run: cargo clippy --all -- -Dwarning -Adead_code
      - name: test
        run: cargo test --verbose

  tsc:
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.2.0
      - name: npminstall
        run: npm install
      - name: build
        run: npx tsc


