name: deploy

on:
  push:
    branches: [ "master" ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: init-ssh-key
        run: mkdir -p ~/.ssh && echo '${{ secrets.AZURE_SSH_PRIVATE_KEY }}' > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519
      - name: init-known-hosts
        run: echo '${{ secrets.AZURE_SSH_KNOWN_HOSTS }}' > ~/.ssh/known_hosts
      - name: copy-to-vm
        run: scp -r . '${{ secrets.AZURE_SSH_USER }}@${{ secrets.AZURE_IP_ADDRESS }}:app'
      - name: setup-env-file
        run: echo '${{ secrets.ENV_FILE }}' > ./env-file && scp ./env-file '${{ secrets.AZURE_SSH_USER }}@${{ secrets.AZURE_IP_ADDRESS }}:app/.env'
      - name: deploy-app
        run: ssh '${{ secrets.AZURE_SSH_USER }}@${{ secrets.AZURE_IP_ADDRESS }}' 'cd app && BUILD=true FORCE_RECREATE=true ./run-dev'

