name: Backend-Api-Cargo

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    defaults:
      run:
        working-directory: ./backend/api
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Clippy
      run: cargo clippy --all -- -D clippy::all -D clippy::pedantic -D clippy::nursery -D clippy::cargo
      env:
        SQLX_OFFLINE: true
    - name: Run tests
      run: cargo test --verbose
      env:
        SQLX_OFFLINE: true
