name: Backend-Api

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo:
    defaults:
      run:
        working-directory: ./backend/api
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: clippy
      run: cargo clippy --all -- -Dwarnings -Adead_code
      env:
        SQLX_OFFLINE: true
    - name: test
      run: cargo test --verbose
      env:
        SQLX_OFFLINE: true
