name: Frontend-Typescript-Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tscBuild:
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup NPM
      uses: actions/setup-node@v4.2.0
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npx tsc
